# @package _global_
model:
  feature_extractor_2d:
    use: false
  volume_size: 32
  explicit_volume: true
  explicit_rendering: true
  unet:
    volume_repr: triplanes
    self_condition: true
    self_condition_images: seen
    self_condition_detach: true
    input_dim: 3
    model_channels: 32
    attention_aggregation: true
    blocks_per_res: 2  
    channel_mult:
    - 1
    - 2
    - 4
    - 8
    attn_resolutions:
    - 16
    - 8
    - 4