wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.16
    start_time: 1699604306.610199
    t:
      1:
      - 1
      - 9
      - 41
      - 50
      - 55
      - 71
      2:
      - 1
      - 9
      - 41
      - 50
      - 55
      - 71
      3:
      - 16
      - 23
      4: 3.8.16
      5: 0.14.0
      8:
      - 5
data:
  desc: null
  value:
    always_drop_at_least_one_view: true
    background: white
    category: hydrant
    data_path: /home/hoellein/git/viewset-diffusion/outputs/co3d
    dataset_type: co3d
    encode_pose: true
    encode_rays: true
    input_size:
    - 128
    - 128
    one_training_img_per_example: false
    rotation_augmentation: true
    sequence_idx: None
    translation_augmentation: 0.0
    two_training_imgs_per_example: false
    white_background: false
eval:
  desc: null
  value:
    sampling_timesteps: 250
    save_every: 2000
general:
  desc: null
  value:
    devices: 1
    random_seed: 0
model:
  desc: null
  value:
    diffuser:
      beta_schedule: cosine
      steps: 1000
    explicit_rendering: true
    explicit_volume: true
    feature_extractor_2d:
      pass_features: both
      res_blocks: 2
      use: true
    hidden_dim: 64
    input_dim: 9
    n_heads: 1
    unet:
      attention_aggregation: true
      attn_resolutions:
      - 16
      - 8
      - 4
      blocks_per_res: 2
      channel_mult:
      - 1
      - 2
      - 4
      - 8
      input_dim: 64
      model_channels: 64
      self_condition: true
      self_condition_detach: true
      self_condition_images: seen
      volume_repr: voxel
    volume_size: 32
optimization:
  desc: null
  value:
    accumulate_grad_steps: 1
    batch_size: 8
    betas:
    - 0.9
    - 0.99
    clamp_min_snr: true
    continue_from_checkpoint: none
    ema:
      decay: 0.995
      update_every: 10
      use: true
    hard_mining_proportion: 0.9
    keep_clean_only_proportion: 0.0
    loss: l2
    lr: 2.0e-05
    n_iter: 300001
    noisy_dropout_proportion: 0.5
    normalize_unseen_to_a_third: true
    penalize: seen_and_one_more
    save_every: 2000
    weigh_clean: true
    weigh_loss_unseen: 0.1
    weigh_terms: true
render:
  desc: null
  value:
    aspect_ratio: 1
    fov: 15.0
    max_depth: 7.5
    min_depth: 0.0001
    n_pts_per_ray: 96
    n_pts_per_ray_fine: 32
    post_activation: true
    raw_noise_std: 0.0
    stratified_sampling: true
    volume_extent_world: 1.2
    volume_offsets:
    - 0.0
    - 0.0
    - 0.0
    volume_size: 32
    volume_size_mults:
    - 1.0
    - 1.0
    - 1.0
    zfar: 10.0
    znear: 0.1
wandb:
  desc: null
  value:
    model: online
    project: mine
